2021-11-12 09:09:31 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration lovelace_gen which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hpprinter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration weatherbit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration myenergi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration media_player_template which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration mail_and_packages which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration myq which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:31 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 09:09:49 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 18c5cb337b92361e3c2bedca7a9415625191a874607fa635050bccb53054adbe from 192.168.1.1
2021-11-12 09:09:50 WARNING (SyncWorker_9) [homeassistant.components.local_file.camera] Could not read camera mail_usps image from file: /custom_components/mail_and_packages/mail_none.gif
2021-11-12 09:09:51 WARNING (MainThread) [alexapy.alexalogin] No access token found; falling back to credential login instead of oauth.
2021-11-12 09:09:55 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2021-11-12 09:10:05 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.115 @ 192.168.1.115: Error connecting to ('192.168.1.115', 6053): [Errno 113] Connect call failed ('192.168.1.115', 6053)
2021-11-12 09:10:07 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input '<template TemplateState(<state sensor.ddwart_run_time_mins=8227.52; unit_of_measurement=mins, friendly_name=DDWart Run Time @ 2021-11-12T09:10:07.083927-05:00>)>' when rendering template '{% set time = (states.sensor.ddwart_run_time_mins | int) | int %} {% set minutes = ((time % 3600) / 60) | int %} {% set hours = ((time % 86400) / 3600) | int %} {% set days = (time / 86400) | int %}
{% if time == 0 %}
  Just restarted...
 {%- else -%}
  {%- if days > 0 -%}
    {{ days }}d
  {%- endif -%}
  {%- if hours > 0 -%}
    {%- if days > 0 -%}
      {{ ' ' }}
    {%- endif -%}
    {{ hours }}h
  {%- endif -%}
  {%- if minutes > 0 -%}
    {%- if days > 0 or hours > 0 -%}
      {{ ' ' }}
    {%- endif -%}
    {{ minutes }}m
  {%- endif -%}
{%- endif -%}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 09:10:07 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input '<template TemplateState(<state sensor.ddwart_run_time_mins=8227.52; unit_of_measurement=mins, friendly_name=DDWart Run Time @ 2021-11-12T09:10:07.083927-05:00>)>' when rendering template '{% set time = (states.sensor.ddwart_run_time_mins | int) | int %} {% set minutes = ((time % 3600) / 60) | int %} {% set hours = ((time % 86400) / 3600) | int %} {% set days = (time / 86400) | int %}
{% if time == 0 %}
  Just restarted...
 {%- else -%}
  {%- if days > 0 -%}
    {{ days }}d
  {%- endif -%}
  {%- if hours > 0 -%}
    {%- if days > 0 -%}
      {{ ' ' }}
    {%- endif -%}
    {{ hours }}h
  {%- endif -%}
  {%- if minutes > 0 -%}
    {%- if days > 0 or hours > 0 -%}
      {{ ' ' }}
    {%- endif -%}
    {{ minutes }}m
  {%- endif -%}
{%- endif -%}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 09:10:07 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input '<template TemplateState(<state sensor.netgear_r6400_v2_ewvisualarts_uptime=493651; unit_of_measurement=s, friendly_name=Netgear R6400 v2:EWVisualArts Uptime, icon=mdi:server-network @ 2021-11-12T09:10:05.369671-05:00>)>' when rendering template '{% set uptime = states.sensor.netgear_r6400_v2_ewvisualarts_uptime | int %} {% set days = (uptime / 86400) | int %} {%- if days > 0 -%}
  {{ days }} days, {{ (uptime - (days * 86400)) | int | timestamp_custom('%H:%M:%S', false) }}
{%- else -%}
  {{ uptime | int | timestamp_custom('%H:%M:%S', false) }}
{%- endif -%}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 09:10:07 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input '<template TemplateState(<state sensor.netgear_r6400_v2_ewvisualarts_uptime=493651; unit_of_measurement=s, friendly_name=Netgear R6400 v2:EWVisualArts Uptime, icon=mdi:server-network @ 2021-11-12T09:10:05.369671-05:00>)>' when rendering template '{% set uptime = states.sensor.netgear_r6400_v2_ewvisualarts_uptime | int %} {% set days = (uptime / 86400) | int %} {%- if days > 0 -%}
  {{ days }} days, {{ (uptime - (days * 86400)) | int | timestamp_custom('%H:%M:%S', false) }}
{%- else -%}
  {{ uptime | int | timestamp_custom('%H:%M:%S', false) }}
{%- endif -%}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 09:10:10 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'unavailable' when rendering template '{% set up_time =  as_timestamp(now()) - as_timestamp(states('sensor.ewvisualarts_last_boot')) %}
{% if up_time == 0 %}
  Just restarted...
{% else %}
  {% set minutes = (up_time // 60) | int %}
  {% set hours = (minutes // 60) %}
  {% set days = (hours // 24) %}
  {% set weeks = (days // 7) %}

  {% set minutes = (minutes % 60) %}
  {% set hours =  (hours % 24) %}
  {% set days = (days % 7) %}

  {% macro phrase(value, name) %}
            {%- set value = value %}
            {%- set end = 's' if value > 1 else '' %}
            {{- '{} {}{}'.format(value, name, end) if value | int > 0 else '' }}
  {%- endmacro %}

  {% set text = [ phrase(weeks, 'week'), phrase(days, 'day'), phrase(hours, 'hr'), phrase(minutes, 'min') ] | select('!=','') | list | join(', ') %}
  {% set last_comma = text.rfind(',') %}
  {% if last_comma != -1 %}
    {% set text = text[:last_comma] + '' + text[last_comma + 1:] %}
  {% endif %}

{{ text }}
{% endif %}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-12 09:10:10 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'') while processing template 'Template("{% set up_time =  as_timestamp(now()) - as_timestamp(states('sensor.ewvisualarts_last_boot')) %}
{% if up_time == 0 %}
  Just restarted...
{% else %}
  {% set minutes = (up_time // 60) | int %}
  {% set hours = (minutes // 60) %}
  {% set days = (hours // 24) %}
  {% set weeks = (days // 7) %}

  {% set minutes = (minutes % 60) %}
  {% set hours =  (hours % 24) %}
  {% set days = (days % 7) %}

  {% macro phrase(value, name) %}
            {%- set value = value %}
            {%- set end = 's' if value > 1 else '' %}
            {{- '{} {}{}'.format(value, name, end) if value | int > 0 else '' }}
  {%- endmacro %}

  {% set text = [ phrase(weeks, 'week'), phrase(days, 'day'), phrase(hours, 'hr'), phrase(minutes, 'min') ] | select('!=','') | list | join(', ') %}
  {% set last_comma = text.rfind(',') %}
  {% if last_comma != -1 %}
    {% set text = text[:last_comma] + '' + text[last_comma + 1:] %}
  {% endif %}

{{ text }}
{% endif %}")' for attribute '_attr_native_value' in entity 'sensor.uptime_synology_nas'
2021-11-12 09:10:11 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 162, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-12 09:10:11 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 368, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-12 09:10:11 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 134, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-12 09:10:11 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 85, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-12 09:10:28 WARNING (MainThread) [homeassistant.components.media_player] Updating alexa_media media_player took longer than the scheduled update interval 0:00:10
2021-11-12 09:10:32 WARNING (MainThread) [homeassistant.components.media_player] Updating webostv media_player took longer than the scheduled update interval 0:00:10
2021-11-12 09:10:41 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.desktop_daily_energy has unknown unit W
2021-11-12 09:10:41 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.ewva_daily_energy has unknown unit W
2021-11-12 09:10:41 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.sink_light_daily_energy has unknown unit W
2021-11-12 09:10:41 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.cabinet_lights_daily_energy has unknown unit W
2021-11-12 09:10:41 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.master_bath_light_daily_energy has unknown unit W
2021-11-12 09:10:41 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.master_bath_fan_daily_energy has unknown unit W
2021-11-12 09:10:41 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.pond_aerator_daily_energy has unknown unit kW
2021-11-12 09:10:41 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.counter_lights_daily_energy has unknown unit kW
2021-11-12 09:10:41 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.tooster_daily_energy has unknown unit kW
2021-11-12 09:26:51 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.104 @ 192.168.1.104: Timeout while connecting to ('192.168.1.104', 6053)
2021-11-12 09:38:57 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.104 @ 192.168.1.104: Timeout while connecting to ('192.168.1.104', 6053)
2021-11-12 10:05:58 WARNING (MainThread) [custom_components.mail_and_packages.camera] Could not read camera Mail USPS Camera image from file: /config/custom_components/mail_and_packages/images/bb450420-676e-46a2-b589-27471501805f.gif
2021-11-12 10:18:01 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.64 @ 192.168.1.64: Timeout while connecting to ('192.168.1.64', 6053)
2021-11-12 10:21:21 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.124 @ 192.168.1.124: Error connecting to ('192.168.1.124', 6053): [Errno 113] Connect call failed ('192.168.1.124', 6053)
2021-11-12 10:41:32 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.dining_room_heating_ratio (<class 'homeassistant.components.history_stats.sensor.HistoryStatsSensor'>) took 0.918 seconds. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+history_stats%22
2021-11-12 11:08:35 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.64 @ 192.168.1.64: Timeout while connecting to ('192.168.1.64', 6053)
2021-11-12 11:11:53 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.64 @ 192.168.1.64: Timeout while connecting to ('192.168.1.64', 6053)
2021-11-12 11:30:50 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.104 @ 192.168.1.104: Timeout while connecting to ('192.168.1.104', 6053)
2021-11-12 11:43:39 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.124 @ 192.168.1.124: Error connecting to ('192.168.1.124', 6053): [Errno 113] Connect call failed ('192.168.1.124', 6053)
2021-11-12 11:56:31 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities xxxxx.xxxx_xxxxx
2021-11-12 11:58:13 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities xxxxx.xxxx_xxxxx
2021-11-12 11:59:09 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.124 @ 192.168.1.124: Error connecting to ('192.168.1.124', 6053): [Errno 113] Connect call failed ('192.168.1.124', 6053)
2021-11-12 12:02:14 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.104 @ 192.168.1.104: Timeout while connecting to ('192.168.1.104', 6053)
2021-11-12 12:33:59 WARNING (MainThread) [custom_components.mail_and_packages.camera] Could not read camera Mail USPS Camera image from file: /config/custom_components/mail_and_packages/images/bb450420-676e-46a2-b589-27471501805f.gif
2021-11-12 13:23:00 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.120 @ 192.168.1.120: Error connecting to ('192.168.1.120', 6053): [Errno 113] Connect call failed ('192.168.1.120', 6053)
2021-11-12 14:37:58 ERROR (MainThread) [homeassistant] Error doing job: Fatal error: protocol.eof_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 882, in _read_ready__on_eof
    keep_open = self._protocol.eof_received()
  File "/usr/local/lib/python3.9/site-packages/aiohomekit/controller/ip/connection.py", line 112, in eof_received
    self.close()
  File "/usr/local/lib/python3.9/site-packages/aiohomekit/controller/ip/connection.py", line 120, in close
    result.set_exception(AccessoryDisconnectedError("Connection closed"))
asyncio.exceptions.InvalidStateError: invalid state
2021-11-12 14:48:47 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x4AAE:1:0x0001]: async_initialize: all attempts have failed: [TimeoutError(), DeliveryError('[0x4aae:1:0x0001]: Message send failure'), DeliveryError('[0x4aae:1:0x0001]: Message send failure'), DeliveryError('[0x4aae:1:0x0001]: Message send failure')]
2021-11-12 14:48:48 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x4AAE:1:0x0500]: async_initialize: all attempts have failed: [TimeoutError(), DeliveryError('[0x4aae:1:0x0500]: Message send failure'), DeliveryError('[0x4aae:1:0x0500]: Message send failure'), DeliveryError('[0x4aae:1:0x0500]: Message send failure')]
2021-11-12 15:10:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'value3' is undefined when rendering '{{ value1 }} {{ value2 }} {{ value3 }}'
2021-11-12 15:10:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'target_id' is undefined when rendering '{{ target_id }}'
2021-11-12 15:10:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'content_type' is undefined when rendering '{{ content_type }}'
2021-11-12 15:10:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'channel_id' is undefined when rendering '{{ channel_id }}'
2021-11-12 15:10:52 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'importance_id' is undefined when rendering '{{ importance_id }}'
2021-11-12 16:47:52 WARNING (SyncWorker_11) [homeassistant.loader] We found a custom integration lovelace_gen which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration myq which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_14) [homeassistant.loader] We found a custom integration hpprinter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_9) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration myenergi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_17) [homeassistant.loader] We found a custom integration mail_and_packages which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_16) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration weatherbit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_12) [homeassistant.loader] We found a custom integration media_player_template which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_10) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_11) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 16:47:52 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-12 17:10:14 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'value3' is undefined when rendering '{{ value1 }} {{ value2 }} {{ value3 }}'
2021-11-12 17:10:14 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'target_id' is undefined when rendering '{{ target_id }}'
2021-11-12 17:10:14 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'content_type' is undefined when rendering '{{ content_type }}'
2021-11-12 17:10:14 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'channel_id' is undefined when rendering '{{ channel_id }}'
2021-11-12 17:10:14 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'importance_id' is undefined when rendering '{{ importance_id }}'
2021-11-12 17:10:35 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'value3' is undefined when rendering '{{ value1 }} {{ value2 }} {{ value3 }}'
2021-11-12 17:10:35 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'target_id' is undefined when rendering '{{ target_id }}'
2021-11-12 17:10:35 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'content_type' is undefined when rendering '{{ content_type }}'
2021-11-12 17:10:35 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'channel_id' is undefined when rendering '{{ channel_id }}'
2021-11-12 17:10:35 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'importance_id' is undefined when rendering '{{ importance_id }}'
2021-11-12 18:33:47 ERROR (MainThread) [homeassistant.components.uptimerobot] Error fetching uptimerobot data: Request timeout for 'https://api.uptimerobot.com/v2/getMonitors'
2021-11-12 19:40:19 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.80 @ 192.168.1.80: Timeout while connecting to ('192.168.1.80', 6053)
2021-11-12 19:46:40 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.spare_livingroom_occupancy is taking over 10 seconds
2021-11-12 20:16:40 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.80 @ 192.168.1.80: Timeout while connecting to ('192.168.1.80', 6053)
2021-11-12 20:17:52 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.80 @ 192.168.1.80: Timeout while connecting to ('192.168.1.80', 6053)
2021-11-12 20:28:45 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.128 @ 192.168.1.128: Timeout while connecting to ('192.168.1.128', 6053)
2021-11-12 20:30:27 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.128 @ 192.168.1.128: Timeout while connecting to ('192.168.1.128', 6053)
2021-11-12 20:31:58 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.128 @ 192.168.1.128: Timeout while connecting to ('192.168.1.128', 6053)
2021-11-12 20:37:53 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.80 @ 192.168.1.80: Timeout while connecting to ('192.168.1.80', 6053)
2021-11-12 20:40:05 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.80 @ 192.168.1.80: Timeout while connecting to ('192.168.1.80', 6053)
2021-11-12 20:44:58 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.80 @ 192.168.1.80: Timeout while connecting to ('192.168.1.80', 6053)
2021-11-12 21:05:53 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.128 @ 192.168.1.128: Timeout waiting for response for <class 'api_pb2.ConnectRequest'>
2021-11-12 21:11:32 WARNING (MainThread) [homeassistant.components.esphome] Error getting initial data for 192.168.1.123: Timeout waiting for response for <class 'api_pb2.ListEntitiesRequest'>
2021-11-12 21:20:07 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.80 @ 192.168.1.80: Error connecting to ('192.168.1.80', 6053): [Errno 113] Connect call failed ('192.168.1.80', 6053)
2021-11-12 21:32:06 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.80 @ 192.168.1.80: Timeout while connecting to ('192.168.1.80', 6053)
2021-11-12 21:35:40 ERROR (MainThread) [custom_components.myq] Timeout fetching myq devices data
2021-11-12 21:42:32 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /homeassistant/restart request Server disconnected
