2021-11-13 12:34:59 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration weatherbit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration lovelace_gen which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration myenergi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hpprinter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration myq which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration media_player_template which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:34:59 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration mail_and_packages which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-13 12:35:33 WARNING (SyncWorker_4) [homeassistant.components.local_file.camera] Could not read camera mail_usps image from file: /custom_components/mail_and_packages/mail_none.gif
2021-11-13 12:35:33 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2021-11-13 12:35:33 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2021-11-13 12:35:34 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2021-11-13 12:35:34 WARNING (MainThread) [homeassistant.components.weather] Setup of weather platform pirateweather is taking over 10 seconds.
2021-11-13 12:35:34 WARNING (MainThread) [alexapy.alexalogin] No access token found; falling back to credential login instead of oauth.
2021-11-13 12:35:34 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Home' for accuweather integration not ready yet; Retrying in background
2021-11-13 12:35:35 WARNING (MainThread) [homeassistant.config_entries] Config entry 'benchdog93@gmail.com' for uptimerobot integration not ready yet: Request timeout for 'https://api.uptimerobot.com/v2/getMonitors'; Retrying in background
2021-11-13 12:35:42 WARNING (MainThread) [homeassistant.setup] Setup of webostv is taking over 10 seconds.
2021-11-13 12:35:44 WARNING (MainThread) [homeassistant.setup] Setup of automation is taking over 10 seconds.
2021-11-13 12:35:45 WARNING (MainThread) [homeassistant.setup] Setup of script is taking over 10 seconds.
2021-11-13 12:35:56 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.115 @ 192.168.1.115: Error connecting to ('192.168.1.115', 6053): [Errno 113] Connect call failed ('192.168.1.115', 6053)
2021-11-13 12:35:56 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform pirateweather is taking over 10 seconds.
2021-11-13 12:36:03 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input '<template TemplateState(<state sensor.ddwart_run_time_mins=45.03; unit_of_measurement=mins, friendly_name=DDWart Run Time @ 2021-11-13T12:36:03.797717-05:00>)>' when rendering template '{% set time = (states.sensor.ddwart_run_time_mins | int) | int %} {% set minutes = ((time % 3600) / 60) | int %} {% set hours = ((time % 86400) / 3600) | int %} {% set days = (time / 86400) | int %}
{% if time == 0 %}
  Just restarted...
 {%- else -%}
  {%- if days > 0 -%}
    {{ days }}d
  {%- endif -%}
  {%- if hours > 0 -%}
    {%- if days > 0 -%}
      {{ ' ' }}
    {%- endif -%}
    {{ hours }}h
  {%- endif -%}
  {%- if minutes > 0 -%}
    {%- if days > 0 or hours > 0 -%}
      {{ ' ' }}
    {%- endif -%}
    {{ minutes }}m
  {%- endif -%}
{%- endif -%}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-13 12:36:03 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input '<template TemplateState(<state sensor.ddwart_run_time_mins=45.03; unit_of_measurement=mins, friendly_name=DDWart Run Time @ 2021-11-13T12:36:03.797717-05:00>)>' when rendering template '{% set time = (states.sensor.ddwart_run_time_mins | int) | int %} {% set minutes = ((time % 3600) / 60) | int %} {% set hours = ((time % 86400) / 3600) | int %} {% set days = (time / 86400) | int %}
{% if time == 0 %}
  Just restarted...
 {%- else -%}
  {%- if days > 0 -%}
    {{ days }}d
  {%- endif -%}
  {%- if hours > 0 -%}
    {%- if days > 0 -%}
      {{ ' ' }}
    {%- endif -%}
    {{ hours }}h
  {%- endif -%}
  {%- if minutes > 0 -%}
    {%- if days > 0 or hours > 0 -%}
      {{ ' ' }}
    {%- endif -%}
    {{ minutes }}m
  {%- endif -%}
{%- endif -%}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-13 12:36:03 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input '<template TemplateState(<state sensor.netgear_r6400_v2_ewvisualarts_uptime=2702; unit_of_measurement=s, friendly_name=Netgear R6400 v2:EWVisualArts Uptime, icon=mdi:server-network @ 2021-11-13T12:35:57.898684-05:00>)>' when rendering template '{% set uptime = states.sensor.netgear_r6400_v2_ewvisualarts_uptime | int %} {% set days = (uptime / 86400) | int %} {%- if days > 0 -%}
  {{ days }} days, {{ (uptime - (days * 86400)) | int | timestamp_custom('%H:%M:%S', false) }}
{%- else -%}
  {{ uptime | int | timestamp_custom('%H:%M:%S', false) }}
{%- endif -%}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-13 12:36:03 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'int' got invalid input '<template TemplateState(<state sensor.netgear_r6400_v2_ewvisualarts_uptime=2702; unit_of_measurement=s, friendly_name=Netgear R6400 v2:EWVisualArts Uptime, icon=mdi:server-network @ 2021-11-13T12:35:57.898684-05:00>)>' when rendering template '{% set uptime = states.sensor.netgear_r6400_v2_ewvisualarts_uptime | int %} {% set days = (uptime / 86400) | int %} {%- if days > 0 -%}
  {{ days }} days, {{ (uptime - (days * 86400)) | int | timestamp_custom('%H:%M:%S', false) }}
{%- else -%}
  {{ uptime | int | timestamp_custom('%H:%M:%S', false) }}
{%- endif -%}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-13 12:36:09 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.desktop_daily_energy has unknown unit W
2021-11-13 12:36:09 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.ewva_daily_energy has unknown unit W
2021-11-13 12:36:09 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.sink_light_daily_energy has unknown unit W
2021-11-13 12:36:09 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.cabinet_lights_daily_energy has unknown unit W
2021-11-13 12:36:09 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.master_bath_light_daily_energy has unknown unit W
2021-11-13 12:36:09 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.master_bath_fan_daily_energy has unknown unit W
2021-11-13 12:36:09 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.pond_aerator_daily_energy has unknown unit kW
2021-11-13 12:36:09 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input 'unavailable' when rendering template '{% set up_time =  as_timestamp(now()) - as_timestamp(states('sensor.ewvisualarts_last_boot')) %}
{% if up_time == 0 %}
  Just restarted...
{% else %}
  {% set minutes = (up_time // 60) | int %}
  {% set hours = (minutes // 60) %}
  {% set days = (hours // 24) %}
  {% set weeks = (days // 7) %}

  {% set minutes = (minutes % 60) %}
  {% set hours =  (hours % 24) %}
  {% set days = (days % 7) %}

  {% macro phrase(value, name) %}
            {%- set value = value %}
            {%- set end = 's' if value > 1 else '' %}
            {{- '{} {}{}'.format(value, name, end) if value | int > 0 else '' }}
  {%- endmacro %}

  {% set text = [ phrase(weeks, 'week'), phrase(days, 'day'), phrase(hours, 'hr'), phrase(minutes, 'min') ] | select('!=','') | list | join(', ') %}
  {% set last_comma = text.rfind(',') %}
  {% if last_comma != -1 %}
    {% set text = text[:last_comma] + '' + text[last_comma + 1:] %}
  {% endif %}

{{ text }}
{% endif %}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-13 12:36:09 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'') while processing template 'Template("{% set up_time =  as_timestamp(now()) - as_timestamp(states('sensor.ewvisualarts_last_boot')) %}
{% if up_time == 0 %}
  Just restarted...
{% else %}
  {% set minutes = (up_time // 60) | int %}
  {% set hours = (minutes // 60) %}
  {% set days = (hours // 24) %}
  {% set weeks = (days // 7) %}

  {% set minutes = (minutes % 60) %}
  {% set hours =  (hours % 24) %}
  {% set days = (days % 7) %}

  {% macro phrase(value, name) %}
            {%- set value = value %}
            {%- set end = 's' if value > 1 else '' %}
            {{- '{} {}{}'.format(value, name, end) if value | int > 0 else '' }}
  {%- endmacro %}

  {% set text = [ phrase(weeks, 'week'), phrase(days, 'day'), phrase(hours, 'hr'), phrase(minutes, 'min') ] | select('!=','') | list | join(', ') %}
  {% set last_comma = text.rfind(',') %}
  {% if last_comma != -1 %}
    {% set text = text[:last_comma] + '' + text[last_comma + 1:] %}
  {% endif %}

{{ text }}
{% endif %}")' for attribute '_attr_native_value' in entity 'sensor.uptime_synology_nas'
2021-11-13 12:36:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.counter_lights_daily_energy has unknown unit kW
2021-11-13 12:36:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.tooster_daily_energy has unknown unit kW
2021-11-13 12:36:10 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 162, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-13 12:36:10 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 368, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-13 12:36:10 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 134, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-13 12:36:10 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry 192.168.1.24 for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 85, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-13 12:36:12 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.124 @ 192.168.1.124: Error connecting to ('192.168.1.124', 6053): [Errno 113] Connect call failed ('192.168.1.124', 6053)
2021-11-13 12:36:47 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'value3' is undefined when rendering '{{ value1 }} {{ value2 }} {{ value3 }}'
2021-11-13 12:36:47 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'target_id' is undefined when rendering '{{ target_id }}'
2021-11-13 12:36:47 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'content_type' is undefined when rendering '{{ content_type }}'
2021-11-13 12:36:47 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'channel_id' is undefined when rendering '{{ channel_id }}'
2021-11-13 12:36:47 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'importance_id' is undefined when rendering '{{ importance_id }}'
2021-11-13 12:44:41 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.198 @ 192.168.1.198: Timeout while connecting to ('192.168.1.198', 6053)
2021-11-13 12:45:26 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.80 @ 192.168.1.80: Timeout while connecting to ('192.168.1.80', 6053)
2021-11-13 12:46:26 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.81 @ 192.168.1.81: Timeout while connecting to ('192.168.1.81', 6053)
2021-11-13 13:42:05 WARNING (MainThread) [custom_components.mail_and_packages.camera] Could not read camera Mail USPS Camera image from file: /config/custom_components/mail_and_packages/images/bb450420-676e-46a2-b589-27471501805f.gif
2021-11-13 14:05:30 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.198 @ 192.168.1.198: Timeout while connecting to ('192.168.1.198', 6053)
2021-11-13 14:13:58 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.81 @ 192.168.1.81: Error connecting to ('192.168.1.81', 6053): [Errno 113] Connect call failed ('192.168.1.81', 6053)
2021-11-13 14:25:00 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140072133683088] Client unable to keep up with pending messages. Stayed over 512 for 5 seconds
2021-11-13 14:25:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140072133683088] Client unable to keep up with pending messages. Stayed over 512 for 5 seconds
2021-11-13 14:33:26 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.nodeid_21_switch
2021-11-13 14:33:27 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.nodeid_18_switch
2021-11-13 14:33:27 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.nodeid_19_switch
2021-11-13 14:33:27 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.nodeid_20_switch
2021-11-13 14:33:27 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.nodeid_20_switch
2021-11-13 14:33:28 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.balcony_chandelier, light.kitchen_light_2, light.livingroom_receptacle_on_off, light.shelly_shbduo_1_d0cd10, light.shelly_shbduo_1_d1225f, switch.cabinet_lights_relay_2, switch.sink_light_relay_2
2021-11-13 14:58:06 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.198 @ 192.168.1.198: Timeout while connecting to ('192.168.1.198', 6053)
2021-11-13 15:14:07 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.80 @ 192.168.1.80: Timeout while connecting to ('192.168.1.80', 6053)
2021-11-13 15:38:58 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.80 @ 192.168.1.80: Timeout while connecting to ('192.168.1.80', 6053)
2021-11-13 15:55:42 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.80 @ 192.168.1.80: Timeout while connecting to ('192.168.1.80', 6053)
2021-11-13 16:36:27 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'value3' is undefined when rendering '{{ value1 }} {{ value2 }} {{ value3 }}'
2021-11-13 16:36:27 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'target_id' is undefined when rendering '{{ target_id }}'
2021-11-13 16:36:27 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'content_type' is undefined when rendering '{{ content_type }}'
2021-11-13 16:36:27 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'channel_id' is undefined when rendering '{{ channel_id }}'
2021-11-13 16:36:27 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'importance_id' is undefined when rendering '{{ importance_id }}'
2021-11-13 17:14:15 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.198 @ 192.168.1.198: Timeout while connecting to ('192.168.1.198', 6053)
2021-11-13 18:38:14 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.80 @ 192.168.1.80: Timeout while connecting to ('192.168.1.80', 6053)
2021-11-13 18:56:57 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.186 @ 192.168.1.186: Timeout while connecting to ('192.168.1.186', 6053)
2021-11-13 18:59:40 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.60 @ 192.168.1.60: Timeout while connecting to ('192.168.1.60', 6053)
2021-11-13 19:01:32 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.65 @ 192.168.1.65: Timeout while connecting to ('192.168.1.65', 6053)
2021-11-13 19:11:20 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 57, in _handle
    return await self._handle_request(request, token, path)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 154, in _handle_request
    await response.write(data)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_response.py", line 470, in write
    await self._payload_writer.write(data)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_writer.py", line 107, in write
    self._write(chunk)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2021-11-13 19:38:37 WARNING (MainThread) [custom_components.mail_and_packages.camera] Could not read camera Mail USPS Camera image from file: /config/custom_components/mail_and_packages/images/bb450420-676e-46a2-b589-27471501805f.gif
2021-11-13 19:41:31 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for 192.168.1.80 @ 192.168.1.80: Timeout while connecting to ('192.168.1.80', 6053)
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending Zigbee broadcast with tsn 249 under 250 request id, data: b'f93c00'
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (17, 250, 0, <DeconzAddressEndpoint address_mode=1 address=65532 endpoint=None>, 0, 54, 0, b'\xf9<\x00', 2, 0)
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x12f90018001100fa0001fcff00003600000300f93c000200
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x12f9000900020022fa
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.api] APS data request response: [2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, 250]
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0efa000700aa00
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 170>, 0]
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x17fa000800010001
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x17fa0021001a002201fcff0102000000000036000300f93c0000af11155c010015
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [26, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.GROUP address=0xfffc>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 0, 0, 54, b'\xf9<\x00', 0, 175, 17, 21, 92, 1, 0, 21]
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy.zdo] [0x0000:zdo] ZDO request ZDOCmd.Mgmt_Permit_Joining_req: [60, <Bool.false: 0>]
2021-11-13 19:45:48 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x0000](ConBee II): started initialization
2021-11-13 19:45:48 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [0x0000:ZDO](ConBee II): 'async_initialize' stage succeeded
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, ep: 0, profile: 0x0000, cluster_id: 0x0036, data: b'f93c00'
2021-11-13 19:45:48 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x0000](ConBee II): power source: Mains
2021-11-13 19:45:48 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x0000](ConBee II): completed initialization
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0efb000700a600
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_CONFIRM|2: 166>, 0]
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x04fb0007000000
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x04fb0012000b0022fa01fcff000000000000
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 250: 00
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0xfa 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.GROUP address=0xfffc endpoint=None>, status: 0x00
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.api] Command Command.write_parameter (2, <NetworkParameter.permit_join: 33>, b'<')
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x0bfc0009000200213c
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0bfc000800010021
2021-11-13 19:45:48 DEBUG (MainThread) [zigpy_deconz.api] Write parameter permit_join: SUCCESS
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1cfd0012000b00033d28ab23004b1200efc0
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1cfe000c00050002a0dcefc0
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0eff000700aa00
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 170>, 0]
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x17fd000800010001
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x17fd002a0023002202fdff0002a0dc00000013000c0000a0dc3d28ab23004b12008000afef155c0100c0
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [35, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xfffd>, 0, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, 0, 0, 19, b'\x00\xa0\xdc=(\xab#\x00K\x12\x00\x80', 0, 175, 239, 21, 92, 1, 0, -64]
2021-11-13 19:45:59 INFO (MainThread) [zigpy_deconz.zigbee.application] New device joined: 0xdca0, 00:12:4b:00:23:ab:28:3d
2021-11-13 19:45:59 INFO (MainThread) [zigpy.application] Device 0xdca0 (00:12:4b:00:23:ab:28:3d) joined the network
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.application] Device 00:12:4b:00:23:ab:28:3d changed id (0xdca0 => 0xdca0)
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.device] [0xdca0] Skipping initialization, device is fully initialized
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.application] Device is initialized <Device model='DS01' manuf='eWeLink' nwk=0xDCA0 ieee=00:12:4b:00:23:ab:28:3d is_initialized=True>
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Checking quirks for eWeLink DS01 (00:12:4b:00:23:ab:28:3d)
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.xbee.xbee_io.XBeeSensor'>
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {232, 230} {1}
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.xbee.xbee3_io.XBee3Sensor'>
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {232, 230} {1}
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.smartthings.tag_v4.SmartThingsTagV4'>
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Fail because device_type mismatch on at least one endpoint
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.smartthings.multi.SmartthingsMultiPurposeSensor'>
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Fail because input cluster mismatch on at least one endpoint
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.netvox.z308e3ed.Z308E3ED'>
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Fail because input cluster mismatch on at least one endpoint
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.gledopto.soposhgu10.SoposhGU10'>
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {11, 13} {1}
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'bellows.zigbee.application.EZSPCoordinator'>
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.quirks.registry] Fail because device_type mismatch on at least one endpoint
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.zdo] [0xdca0:zdo] ZDO request ZDOCmd.Device_annce: [0xDCA0, 00:12:4b:00:23:ab:28:3d, 128]
2021-11-13 19:45:59 DEBUG (MainThread) [homeassistant.components.zha.core.gateway] device - 56480:00:12:4b:00:23:ab:28:3d entering async_device_initialized - is_new_join: False
2021-11-13 19:45:59 DEBUG (MainThread) [homeassistant.components.zha.core.gateway] device - 56480:00:12:4b:00:23:ab:28:3d has been reset and re-added or its nwk address changed
2021-11-13 19:45:59 DEBUG (MainThread) [homeassistant.components.zha.core.gateway] skipping discovery for previously discovered device - 56480:00:12:4b:00:23:ab:28:3d
2021-11-13 19:45:59 DEBUG (MainThread) [homeassistant.components.zha.core.device] [56480](DS01): started configuration
2021-11-13 19:45:59 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:ZDO](DS01): 'async_configure' stage succeeded
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, ep: 0, profile: 0x0000, cluster_id: 0x0013, data: b'00a0dc3d28ab23004b120080'
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0efe000700aa00
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 170>, 0]
2021-11-13 19:45:59 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0000]: finished channel configuration
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.device] [0xdca0] Extending timeout for 0xfb request
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending Zigbee request with tsn 251 under 252 request id, data: b'00fb000100'
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (20, 252, 0, <DeconzAddressEndpoint address_mode=2 address=56480 endpoint=1>, 260, 1280, 1, b'\x00\xfb\x00\x01\x00', 2, 0)
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x12fe001b001400fc0002a0dc010401000501050000fb0001000200
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy.device] [0xdca0] Extending timeout for 0xfd request
2021-11-13 19:45:59 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending Zigbee request with tsn 253 under 254 request id, data: b'fd3d28ab23004b120001010003689a07ffff2e210001'
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x12fe00090002002afc
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] APS data request response: [2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 42>, 252]
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (37, 254, 0, <DeconzAddressEndpoint address_mode=2 address=56480 endpoint=0>, 0, <ZDOCmd.Bind_req: 0x0021>, 0, b'\xfd=(\xab#\x00K\x12\x00\x01\x01\x00\x03h\x9a\x07\xff\xff.!\x00\x01', 2, 0)
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x12ff002c002500fe0002a0dc0000002100001600fd3d28ab23004b120001010003689a07ffff2e2100010200
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x12ff00090002002afe
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] APS data request response: [2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 42>, 254]
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy.appdb] Device 00:12:4b:00:23:ab:28:3d already exists. Updating it.
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1701000800010001
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x17010025001e002a0200000102a0dc010401000507000901011500000000afef105c0100c0
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [30, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 42>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, 1, 260, 1280, b'\t\x01\x01\x15\x00\x00\x00', 0, 175, 239, 16, 92, 1, 0, -64]
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy.zcl] [0xdca0:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=1 command_id=1>
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy.zcl] [0xdca0:1:0x0500] ZCL request 0x0001: [<ZoneType.Contact_Switch: 21>, 0]
2021-11-13 19:46:00 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0500]: Enroll requested
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy.device] [0xdca0] Extending timeout for 0xff request
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending Zigbee request with tsn 255 under 0 request id, data: b'01ff000000'
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, ep: 1, profile: 0x0104, cluster_id: 0x0500, data: b'09010115000000'
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1702000800010001
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x17020027002000220200000102a0dc0104010005090019020001000000000000afef06340100c0
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [32, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, 1, 260, 1280, b'\x19\x02\x00\x01\x00\x00\x00\x00\x00', 0, 175, 239, 6, 52, 1, 0, -64]
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy.zcl] [0xdca0:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=2 command_id=0>
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy.zcl] [0xdca0:1:0x0500] ZCL request 0x0000: [<ZoneStatus.Alarm_1: 1>, <bitmap8.0: 0>, 0, 0]
2021-11-13 19:46:00 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0500]: Updated alarm state: ZoneStatus.Alarm_1
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, ep: 1, profile: 0x0104, cluster_id: 0x0500, data: b'190200010000000000'
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e03000700a600
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_CONFIRM|2: 166>, 0]
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c04000c00050002a0dcefc0
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e05000700ae00
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|APSDE_DATA_CONFIRM|2: 174>, 0]
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (20, 0, 0, <DeconzAddressEndpoint address_mode=2 address=56480 endpoint=1>, 260, 1280, 1, b'\x01\xff\x00\x00\x00', 2, 0)
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1203001b001400000002a0dc010401000501050001ff0000000200
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x120300090002002e00
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] APS data request response: [2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|APSDE_DATA_CONFIRM|2: 46>, 0]
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x04040007000000
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x04040013000c002afc02a0dc01010000000000
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 252: 00
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0xfc 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0xdca0 endpoint=1>, status: 0x00
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1705000800010001
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x17050027002000220200000102a0dc0104010005090018fb0101000031150000afef185c0100c0
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [32, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, 1, 260, 1280, b'\x18\xfb\x01\x01\x00\x001\x15\x00', 0, 175, 239, 24, 92, 1, 0, -64]
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy.zcl] [0xdca0:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=251 command_id=Command.Read_Attributes_rsp>
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, ep: 1, profile: 0x0104, cluster_id: 0x0500, data: b'18fb01010000311500'
2021-11-13 19:46:00 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0500]: started IASZoneChannel configuration
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy.device] [0xdca0] Extending timeout for 0x01 request
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending Zigbee request with tsn 1 under 2 request id, data: b'013d28ab23004b120001000503689a07ffff2e210001'
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (37, 2, 0, <DeconzAddressEndpoint address_mode=2 address=56480 endpoint=0>, 0, <ZDOCmd.Bind_req: 0x0021>, 0, b'\x01=(\xab#\x00K\x12\x00\x01\x00\x05\x03h\x9a\x07\xff\xff.!\x00\x01', 2, 0)
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1206002c002500020002a0dc0000002100001600013d28ab23004b120001000503689a07ffff2e2100010200
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x120600090002002202
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] APS data request response: [2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, 2]
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e07000700a600
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_CONFIRM|2: 166>, 0]
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c08000c00050002a0dcefc0
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x04070007000000
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e09000700ae00
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|APSDE_DATA_CONFIRM|2: 174>, 0]
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x04070013000c002afe02a0dc00000000000000
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 254: 00
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0xfe 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0xdca0 endpoint=0>, status: 0x00
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:46:00 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1708000800010001
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x17080020001900220200000002a0dc00000021800200fd0000afef185c0100c0
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [25, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 0, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, 0, 0, 32801, b'\xfd\x00', 0, 175, 239, 24, 92, 1, 0, -64]
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, ep: 0, profile: 0x0000, cluster_id: 0x8021, data: b'fd00'
2021-11-13 19:46:01 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0001]: bound 'power' cluster: Status.SUCCESS
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy.device] [0xdca0] Extending timeout for 0x03 request
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending Zigbee request with tsn 3 under 4 request id, data: b'00030600200020100e302a0100210020100e302a01'
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (36, 4, 0, <DeconzAddressEndpoint address_mode=2 address=56480 endpoint=1>, 260, 1, 1, b'\x00\x03\x06\x00 \x00 \x10\x0e0*\x01\x00!\x00 \x10\x0e0*\x01', 2, 0)
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1209002b002400040002a0dc010401010001150000030600200020100e302a0100210020100e302a010200
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x120900090002002204
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] APS data request response: [2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, 4]
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e0a000700a600
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_CONFIRM|2: 166>, 0]
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c0b000c00050002a0dce7bf
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x040a0007000000
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e0c000700ae00
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|APSDE_DATA_CONFIRM|2: 174>, 0]
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x040a0013000c002a0002a0dc01010000000000
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 0: 00
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x00 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0xdca0 endpoint=1>, status: 0x00
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x170b000800010001
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x170b0023001c00220200000102a0dc0104010005050018ff0b000000afef185c0100c0
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [28, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, 1, 260, 1280, b'\x18\xff\x0b\x00\x00', 0, 175, 239, 24, 92, 1, 0, -64]
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy.zcl] [0xdca0:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=255 command_id=Command.Default_Response>
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, ep: 1, profile: 0x0104, cluster_id: 0x0500, data: b'18ff0b0000'
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e0c000700a600
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_CONFIRM|2: 166>, 0]
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c0d000c00050002a0dcefc0
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x040c0007000000
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e0e000700ae00
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|APSDE_DATA_CONFIRM|2: 174>, 0]
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x040c0013000c002a0202a0dc00000000000000
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 2: 00
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x02 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0xdca0 endpoint=0>, status: 0x00
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x170d000800010001
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x170d0020001900220200000002a0dc00000021800200010000afef185c0100c0
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [25, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 0, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, 0, 0, 32801, b'\x01\x00', 0, 175, 239, 24, 92, 1, 0, -64]
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, ep: 0, profile: 0x0000, cluster_id: 0x8021, data: b'0100'
2021-11-13 19:46:01 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0500]: bound 'ias_zone' cluster: Status.SUCCESS
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy.device] [0xdca0] Extending timeout for 0x05 request
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending Zigbee request with tsn 5 under 6 request id, data: b'0005021000f0689a07ffff2e2100'
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (29, 6, 0, <DeconzAddressEndpoint address_mode=2 address=56480 endpoint=1>, 260, 1280, 1, b'\x00\x05\x02\x10\x00\xf0h\x9a\x07\xff\xff.!\x00', 2, 0)
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x120e0024001d00060002a0dc0104010005010e000005021000f0689a07ffff2e21000200
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x120e00090002002206
2021-11-13 19:46:01 DEBUG (MainThread) [zigpy_deconz.api] APS data request response: [2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, 6]
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e0f000700a600
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_CONFIRM|2: 166>, 0]
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c10000c00050002a0dcf7c1
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x040f0007000000
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e11000700ae00
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|APSDE_DATA_CONFIRM|2: 174>, 0]
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x040f0013000c002a0402a0dc01010000000000
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 4: 00
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x04 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0xdca0 endpoint=1>, status: 0x00
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1710000800010001
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x17100022001b00220200000102a0dc010401010004001803070000aff7185c0100c1
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [27, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, 1, 260, 1, b'\x18\x03\x07\x00', 0, 175, 247, 24, 92, 1, 0, -63]
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy.zcl] [0xdca0:1:0x0001] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=3 command_id=Command.Configure_Reporting_rsp>
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, ep: 1, profile: 0x0104, cluster_id: 0x0001, data: b'18030700'
2021-11-13 19:46:02 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0001]: Successfully configured reporting for '{'battery_voltage': (3600, 10800, 1), 'battery_percentage_remaining': (3600, 10800, 1)}' on 'power' cluster: [ConfigureReportingResponseRecord(status=0)]
2021-11-13 19:46:02 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0001]: finished channel configuration
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e11000700a600
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_CONFIRM|2: 166>, 0]
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c12000c00050002a0dcf7c1
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x04110007000000
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x04110013000c00220602a0dc01010000000000
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 6: 00
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x06 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0xdca0 endpoint=1>, status: 0x00
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e12000700aa00
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 170>, 0]
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1712000800010001
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x17120022001b00220200000102a0dc010401000504001805040000aff7185c0100c1
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [27, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, 1, 260, 1280, b'\x18\x05\x04\x00', 0, 175, 247, 24, 92, 1, 0, -63]
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy.zcl] [0xdca0:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=5 command_id=Command.Write_Attributes_rsp>
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, ep: 1, profile: 0x0104, cluster_id: 0x0500, data: b'18050400'
2021-11-13 19:46:02 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0500]: wrote cie_addr: 00:21:2e:ff:ff:07:9a:68 to 'ias_zone' cluster: [WriteAttributesStatusRecord(status=<Status.SUCCESS: 0>)]
2021-11-13 19:46:02 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0500]: Sending pro-active IAS enroll response
2021-11-13 19:46:02 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0500]: finished IASZoneChannel configuration
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy.device] [0xdca0] Extending timeout for 0x07 request
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending Zigbee request with tsn 7 under 8 request id, data: b'0107000000'
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (20, 8, 0, <DeconzAddressEndpoint address_mode=2 address=56480 endpoint=1>, 260, 1280, 1, b'\x01\x07\x00\x00\x00', 2, 0)
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1213001b001400080002a0dc010401000501050001070000000200
2021-11-13 19:46:02 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0000]: 'async_configure' stage succeeded
2021-11-13 19:46:02 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0500]: 'async_configure' stage succeeded
2021-11-13 19:46:02 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0001]: 'async_configure' stage succeeded
2021-11-13 19:46:02 DEBUG (MainThread) [homeassistant.components.zha.core.device] [56480](DS01): completed configuration
2021-11-13 19:46:02 DEBUG (MainThread) [homeassistant.components.zha.core.device] [56480](DS01): stored in registry: ZhaDeviceEntry(name='eWeLink DS01', ieee='00:12:4b:00:23:ab:28:3d', last_seen=1636850762.772576)
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy.device] [0xdca0] Extending timeout for 0x09 request
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending Zigbee request with tsn 9 under 10 request id, data: b'0109400200'
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x121300090002002208
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] APS data request response: [2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, 8]
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (20, 10, 0, <DeconzAddressEndpoint address_mode=2 address=56480 endpoint=1>, 260, 3, 1, b'\x01\t@\x02\x00', 2, 0)
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1214001b0014000a0002a0dc010401030001050001094002000200
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x12140009000200220a
2021-11-13 19:46:02 DEBUG (MainThread) [zigpy_deconz.api] APS data request response: [2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, 10]
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e15000700a600
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_CONFIRM|2: 166>, 0]
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c16000c00050002a0dcffc2
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x04150007000000
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x04150013000c00220802a0dc01010000000000
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 8: 00
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x08 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0xdca0 endpoint=1>, status: 0x00
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e16000700aa00
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 170>, 0]
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1716000800010001
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x17160023001c00220200000102a0dc0104010005050018070b000000aff7215c0100c1
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [28, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, 1, 260, 1280, b'\x18\x07\x0b\x00\x00', 0, 175, 247, 33, 92, 1, 0, -63]
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy.zcl] [0xdca0:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=7 command_id=Command.Default_Response>
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, ep: 1, profile: 0x0104, cluster_id: 0x0500, data: b'18070b0000'
2021-11-13 19:46:03 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c17000c00050002a0dcffc2
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e18000700a600
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_CONFIRM|2: 166>, 0]
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c19000c00050002a0dcf7c1
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x04170007000000
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e1a000700ae00
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|APSDE_DATA_CONFIRM|2: 174>, 0]
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x04170013000c002a0a02a0dc01010000000000
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 10: 00
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x0a 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0xdca0 endpoint=1>, status: 0x00
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1718000800010001
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x17180023001c00220200000102a0dc0104010300050018090b408100afff215c0100c2
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [28, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, 1, 260, 3, b'\x18\t\x0b@\x81', 0, 175, 255, 33, 92, 1, 0, -62]
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy.zcl] [0xdca0:1:0x0003] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=9 command_id=Command.Default_Response>
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, ep: 1, profile: 0x0104, cluster_id: 0x0003, data: b'18090b4081'
2021-11-13 19:46:04 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0003]: executed 'trigger_effect' command with args: '(2, 0)' kwargs: '{}' result: [64, <Status.UNSUP_CLUSTER_COMMAND: 129>]
2021-11-13 19:46:04 DEBUG (MainThread) [homeassistant.components.zha.core.device] [56480](DS01): started initialization
2021-11-13 19:46:04 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:ZDO](DS01): 'async_initialize' stage succeeded
2021-11-13 19:46:04 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0000]: initializing channel: from_cache: False
2021-11-13 19:46:04 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0000]: finished channel initialization
2021-11-13 19:46:04 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0500]: initializing channel: from_cache: False
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy.device] [0xdca0] Extending timeout for 0x0b request
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending Zigbee request with tsn 11 under 12 request id, data: b'000b000000'
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (20, 12, 0, <DeconzAddressEndpoint address_mode=2 address=56480 endpoint=1>, 260, 1280, 1, b'\x00\x0b\x00\x00\x00', 2, 0)
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1219001b0014000c0002a0dc0104010005010500000b0000000200
2021-11-13 19:46:04 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0001]: initializing channel: from_cache: False
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy.device] [0xdca0] Extending timeout for 0x0d request
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending Zigbee request with tsn 13 under 14 request id, data: b'000d0020002100'
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x12190009000200220c
2021-11-13 19:46:04 DEBUG (MainThread) [zigpy_deconz.api] APS data request response: [2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, 12]
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (22, 14, 0, <DeconzAddressEndpoint address_mode=2 address=56480 endpoint=1>, 260, 1, 1, b'\x00\r\x00 \x00!\x00', 2, 0)
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x121a001d0016000e0002a0dc0104010100010700000d00200021000200
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x121a0009000200220e
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] APS data request response: [2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, 14]
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e1b000700a600
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_CONFIRM|2: 166>, 0]
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c1c000c00050002a0dcffc2
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x041b0007000000
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x041b0013000c00220c02a0dc01010000000000
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 12: 00
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x0c 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0xdca0 endpoint=1>, status: 0x00
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e1c000700aa00
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 170>, 0]
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x171c000800010001
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x171c0026001f00220200000102a0dc01040100050800180b01000000300100afff215c0100c2
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [31, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, 1, 260, 1280, b'\x18\x0b\x01\x00\x00\x000\x01', 0, 175, 255, 33, 92, 1, 0, -62]
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy.zcl] [0xdca0:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=11 command_id=Command.Read_Attributes_rsp>
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, ep: 1, profile: 0x0104, cluster_id: 0x0500, data: b'180b010000003001'
2021-11-13 19:46:05 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0500]: finished channel initialization
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c1d000c00050002a0dcffc2
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e1e000700a600
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_CONFIRM|2: 166>, 0]
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x041d0007000000
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x041d0013000c00220e02a0dc01010000000000
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 14: 00
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x0e 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0xdca0 endpoint=1>, status: 0x00
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e1e000700aa00
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|2: 170>, 0]
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x171e000800010001
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x171e002b002400220200000102a0dc01040101000d00180d01200000202021000020c800afff215c0100c2
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [36, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, 1, 260, 1, b'\x18\r\x01 \x00\x00  !\x00\x00 \xc8', 0, 175, 255, 33, 92, 1, 0, -62]
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy.zcl] [0xdca0:1:0x0001] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=13 command_id=Command.Read_Attributes_rsp>
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, ep: 1, profile: 0x0104, cluster_id: 0x0001, data: b'180d01200000202021000020c8'
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy.device] [0xdca0] Extending timeout for 0x0f request
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending Zigbee request with tsn 15 under 16 request id, data: b'000f0031003300'
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (22, 16, 0, <DeconzAddressEndpoint address_mode=2 address=56480 endpoint=1>, 260, 1, 1, b'\x00\x0f\x001\x003\x00', 2, 0)
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x121f001d001600100002a0dc0104010100010700000f00310033000200
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x121f00090002002210
2021-11-13 19:46:05 DEBUG (MainThread) [zigpy_deconz.api] APS data request response: [2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, 16]
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e20000700a600
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_CONFIRM|2: 166>, 0]
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c21000c00050002a0dcffc2
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x04200007000000
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x0e22000700ae00
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.api] Device state changed response: [<DeviceState.128|APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_INDICATION|APSDE_DATA_CONFIRM|2: 174>, 0]
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x04200013000c002a1002a0dc01010000000000
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 16: 00
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x10 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0xdca0 endpoint=1>, status: 0x00
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_indication (1, 1)
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x1721000800010001
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x17210027002000220200000102a0dc01040101000900180f0131008633008600afff215c0100c2
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [32, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 1, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, 1, 260, 1, b'\x18\x0f\x011\x00\x863\x00\x86', 0, 175, 255, 33, 92, 1, 0, -62]
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy.zcl] [0xdca0:1:0x0001] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=15 command_id=Command.Read_Attributes_rsp>
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0xdca0>, ep: 1, profile: 0x0104, cluster_id: 0x0001, data: b'180f01310086330086'
2021-11-13 19:46:06 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0001]: finished channel initialization
2021-11-13 19:46:06 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0000]: 'async_initialize' stage succeeded
2021-11-13 19:46:06 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0500]: 'async_initialize' stage succeeded
2021-11-13 19:46:06 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [56480:1:0x0001]: 'async_initialize' stage succeeded
2021-11-13 19:46:06 DEBUG (MainThread) [homeassistant.components.zha.core.device] [56480](DS01): power source: Battery or Unknown
2021-11-13 19:46:06 DEBUG (MainThread) [homeassistant.components.zha.core.device] [56480](DS01): completed initialization
2021-11-13 19:46:06 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c22000c00050002a0dcf7c1
2021-11-13 19:46:07 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c23000c00050002a0dcffc2
2021-11-13 19:46:08 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c24000c00050002a0dcffc2
2021-11-13 19:46:09 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c25000c00050002a0dcffc2
2021-11-13 19:46:10 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c26000c00050002a0dcffc2
2021-11-13 19:46:11 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c27000c00050002a0dcffc2
2021-11-13 19:46:12 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c28000c00050002a0dcffc3
2021-11-13 19:46:13 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c29000c00050002a0dcffc2
2021-11-13 19:46:14 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x1c2a000c00050002a0dcffc3
2021-11-13 19:52:10 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /homeassistant/restart request Server disconnected
